variables:
  GIT_DEPTH: 0

stages:
  - pylint
  - test
  - docs
  - statistic

pylint-job:
  stage: pylint
  script:
    - pip install -r requirements.txt
    - pylint . --fail-under=8
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days

test-job:
  stage: test
  script:
    - pip install -r requirements.txt
    - coverage run --rcfile=.coveragerc --source='.' manage.py test
    - coverage html -d tests/coverage/
  artifacts:
    paths:
      - tests/coverage/
    expire_in: 30 days

docs-job:
  stage: docs
  script:
    - pip install -r requirements.txt
    - cd docs
    - make html
  artifacts:
    paths:
      - docs/build/
    expire_in: 30 days


statistic-job:
  stage: statistic
  script:
    - python count
