variables:
  GIT_DEPTH: 0

stages:
  - docs
  - pylint

docs-job:
  stage: docs
  script:
    - pip install -r requirements.txt
    - cd docs
    - make html
  artifacts:
    paths:
      - docs/build/
    expire_in: 30 days


pylint-job:
  stage: pylint
  script:
    - pip install -r requirements.txt
    - pylint .
