services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: code_io-web
    command: gunicorn code_io.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_USER=hello_django
      - POSTGRES_DB=hello_django_dev


volumes:
  static_volume:
  media_volume:
  postgres_data:
