version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: hello_django
      POSTGRES_PASSWORD: hello_django
      POSTGRES_DB: hello_django_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hello_django -d hello_django_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    image: codeio-web:latest
    command: python manage.py migrate --noinput
    volumes:
      - .:/app
    depends_on:
      - db
    restart: "no"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: codeio-web:latest
    command: gunicorn code_io.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      - db
      - migrate
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
      # Монтируем сертификаты из хоста
      - /etc/letsencrypt/live/code-io.ru/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/code-io.ru/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
