# Generated by Django 5.1.5 on 2025-02-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.TextField(default='light'),
        ),
    ]
