# Generated by Django 5.1.5 on 2025-02-08 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='text'),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(default='text'),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='text', max_length=200)),
                ('content', models.TextField(default='text')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.course')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='lesson',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.lesson'),
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
