# Generated by Django 5.1.5 on 2025-02-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_course_id_course_id_rename_task_id_task_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='id',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='id',
            new_name='lesson_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='id',
            new_name='task_id',
        ),
    ]
