# Generated by Django 5.1.5 on 2025-02-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tusk',
            new_name='Task',
        ),
    ]
