# Generated by Django 5.1.5 on 2025-04-25 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stars',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='education.courses'),
        ),
    ]
