# Generated by Django 5.1.5 on 2025-04-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_stars_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='topics', to='education.topic'),
        ),
    ]
