# Generated by Django 5.1.5 on 2025-04-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_courses_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='topics',
            field=models.ManyToManyField(to='education.topic'),
        ),
    ]
