# Generated by Django 5.1.5 on 2025-04-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_courseprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='lessons',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
