# Generated by Django 5.1.5 on 2025-04-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_alter_lessons_options_lessons_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={},
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='order',
        ),
        migrations.DeleteModel(
            name='CourseProgress',
        ),
    ]
