# Generated by Django 5.1.5 on 2025-04-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reason',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
