# Generated by Django 5.1.5 on 2025-05-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_report_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='courses', to='education.topic', verbose_name='Темы курса'),
        ),
    ]
