# Generated by Django 5.1.5 on 2025-05-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0018_rename_report_reportcourse_reporttopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttopic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='reporttopic',
            name='reason',
            field=models.CharField(choices=[('spam', 'Спам'), ('illegal', 'Незаконно'), ('Unacceptable', 'Недопустимо')], max_length=50, verbose_name='Причина жалобы'),
        ),
    ]
