# Generated by Django 5.1.5 on 2025-05-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0020_alter_courses_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='lessons',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='lessons',
            unique_together={('course', 'order')},
        ),
    ]
