# Generated by Django 5.1.3 on 2025-05-17 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0023_alter_courses_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttopic',
            name='course',
        ),
        migrations.AddField(
            model_name='reporttopic',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='education.topic', verbose_name='Тег'),
            preserve_default=False,
        ),
    ]
