# Generated by Django 5.1.5 on 2025-02-05 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_rename_name_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.TextField()),
                ('browser', models.TextField()),
                ('browser_version', models.TextField()),
                ('os', models.TextField()),
                ('os_version', models.TextField()),
                ('device', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
