# Generated by Django 5.1.5 on 2025-02-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetrequest',
            name='url',
            field=models.TextField(default=23123),
            preserve_default=False,
        ),
    ]
