# Generated by Django 5.1.5 on 2025-04-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
