# Generated by Django 5.1.3 on 2025-05-16 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
